config/routes.rb
Rails.application.routes.draw do

  root to: 'users#list_friends'
  match '/register', to: 'users#signup', via: [:get, :post], as: :signup
  match '/signin', to: 'users#signin', via: [:get, :post], as: :signin
  get '/logout', to: 'users#logout', as: :logout
  get '/find-friends', to: 'users#find_friend', as: :find_friend
  get '/friends', to: 'users#list_friends', as: :friends
  post '/add-friend', to: 'users#add_friend', as: :add_friend
  post '/update-status-friend/:id', to: 'users#update_status_friend', as: :update_status_friend
  post '/add-friend-favorite', to: 'users#add_friend_favorite', as: :add_friend_favorite
  post '/invite-friend', to: 'users#invite_friend', as: :invite_friend

  get '/profile/:id', to: 'users#profile', as: :profile
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :friends

	# Validation	
	validates_presence_of :email
	validates_uniqueness_of :email
	validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,3})\Z/i
	# validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates_presence_of :password, :on => :create
	# validates_length_of :password ,{:minimum => 2, :maximum => 255, :on => :create}
	validates_strength_of :password, :with => :email, :level => :weak
	validates_length_of :first_name ,{:minimum => 2, :maximum => 255}
	validates_length_of :last_name ,{:minimum => 2, :maximum => 255}

	# Pagination
	self.per_page = 15

	def self.authenticate(email, password)
		user = self.find_by_email(email)
		BCrypt::Engine.hash_secret(password, user.password_digest)
	    if user && user.password_digest == BCrypt::Engine.hash_secret(password, user.password_digest)
	      user
	    else
	      nil
	    end
	end

	def self.quick_search(query)
		@users = User.where('first_name LIKE ? OR last_name LIKE ? OR address LIKE ? OR phone LIKE ? OR email LIKE ?', "%" +query + "%", "%" +query + "%", "%" +query + "%", "%" +query + "%", "%" +query + "%").all
	end

	def self.search(params, user_id)
		keyQuery = ''
		valueQuery = nil
		case params[:type]
		when "name"
			if params[:keyword] != nil && params[:keyword] != ""
				keyQuery += "users.first_name LIKE :first_name OR users.last_name LIKE :last_name"
				valueQuery = {:first_name => "%" + params[:keyword] + "%", :last_name => "%" + params[:keyword] + "%"}
			end
		when "address"
			if params[:keyword] != nil
				keyQuery += "users.address LIKE :address"
				valueQuery = {:address => "%" + params[:keyword] + "%"}
			end
		when "phone"
			if params[:keyword] != nil
				keyQuery += "users.phone LIKE :phone"
				valueQuery = {:phone => "%" + params[:keyword] + "%"}
			end
		when "email"
			if params[:keyword] != nil
				keyQuery += "users.email LIKE :email"
				valueQuery = {:email => "%" + params[:keyword] + "%"}
			end
		else
			if params[:keyword] != nil && params[:keyword] != ""
				keyQuery += "users.first_name LIKE :first_name OR users.last_name LIKE :last_name"
				valueQuery = {:first_name => "%" + params[:keyword] + "%", :last_name => "%" + params[:keyword] + "%"}
			end
		end
		
		orderQuery = 'users.first_name ASC'
		if params[:sort] != nil && params[:order] != nil
			case params[:sort]
			when "name"
				orderQuery = "users.first_name " + params[:order]
			when "friends"
				orderQuery = "COUNT(friends.id) " + params[:order]
			when "favorites"
				orderQuery = "users.points " + params[:order]
			else
				orderQuery = "users.first_name " + params[:order]
			end
		end
		users = User.select("users.*").distinct.joins('LEFT JOIN friends on users.id = friends.user_id')
		if user_id != nil

			if keyQuery != "" && !valueQuery.empty?
				users = users.where('users.id <> ?', user_id).where(keyQuery, valueQuery).page(params[:page]).group('users.id').order(orderQuery)
			else
				users = users.where('users.id <> ?', user_id).page(params[:page]).group('users.id').order(orderQuery)
			end
		else
			if keyQuery != "" && !valueQuery.empty?
				users = users.where(keyQuery, valueQuery).page(params[:page]).group('users.id').order(orderQuery)
			else
				users = users.page(params[:page]).group('users.id').order(orderQuery)
			end
		end
				# binding.pry
	end

	# is_accept = 0 => request
	# 		  = 1 => accept
	# 		  = 2 => reject
	def get_invite_by_frient_id (user_id)
		friend = Friend.where("((user_id = ? AND user_friend_id =?) OR (user_id = ? AND user_friend_id = ?))", user_id, self.id, self.id, user_id).first
		if !friend.nil?
			friend.is_accept
		else
			0
		end
	end

	def fullname
		self.first_name + ' ' + self.last_name
	end

	def self.signup(params)
		user = User.new(params)
	    if user.save
	     	user
		else
			user
	    end
	end

	def self.signin(email, password)
		@user = User.authenticate(params[:session][:email], params[:session][:password])
	  	if 
	    	session[:user_id] = @user.id
	    	redirect_to root_path
	  	else
	  		flash[:message_error] = "Login fail"
	    	redirect_to signin_path()
	  	end 
	end

	# is_accept = 0 => requested
	# 		  = 1 => accept
	# 		  = 2 => reject
	def get_status_friend(user_id)
		if user_id != nil
			friend = self.friends.where('user_friend_id = ?', user_id).first
			if !friend.nil?
				friend.is_accept
			end
		else
			nil
		end
	end
	def get_favorite_friend(user_id)
		if user_id != nil
			friend = Friend.where('user_id = ? AND user_friend_id = ?', user_id, self.id).first
			if !friend.nil?
				friend.is_favorite
			end
		else
			nil
		end
	end

	def get_friends_number
		friends = self.friends.where('is_accept = ?', 1)
		friends.count
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_user, only: [:index]


	def signup
		if request.request_method() == 'POST'
			@user = User.new(user_params)
		    if @user.save
		     	flash[:message_success] = "Register is successful."
		     	session[:user_id] = @user.id
				redirect_to root_path
			else
				flash[:message_error] = "Register isn't successful"
		    end
		else
			@user = User.new
		end
	end

	def signin
		if request.xhr?
			if request.request_method() == 'POST'
				@user = User.authenticate(params[:session][:email], params[:session][:password])
			  	if @user != nil
			    	session[:user_id] = @user.id
			    	# Add friend
			    	friend = Friend.where('(user_id = ? AND user_friend_id = ?) OR (user_id = ? AND user_friend_id = ?)', session[:user_id], params[:session][:id], params[:session][:id], session[:user_id]).first
					if friend.nil?
						friend = Friend.new(:user_id => session[:user_id], :user_friend_id => params[:session][:id], :is_accept => 0)
						friend.save
					end
					#End Add friend

			    	render :json => {status: 1, message: 'Successful'}
			  	else
			  		flash[:message_error] = "Login fail"
			    	render :json => {status: 0, message: 'Error'}
			  	end 
			end
		else
		  	if request.request_method() == 'POST'
				@user = User.authenticate(params[:session][:email], params[:session][:password])
			  	if @user != nil
			    	session[:user_id] = @user.id
			    	redirect_to root_path
			  	else
			  		flash[:message_error] = "Login fail"
			    	redirect_to signin_path()
			  	end 
			end
		end
	end

	def logout
		session[:user_id] = nil
		flash[:message_success] = "Logout is successful"
		redirect_to root_path()
	end

	def find_friend
		if params[:query]
			query = params[:query]
			@users = User.quick_search(query)
			response = []
			@users.each { |item|
				response << {'id' => item.id, 'name' => item.first_name, 'url' => 'abbccb'}
			}
			render :json	 => response
			# return
		end
	end

	def list_friends
		@users = User.search(params,session[:user_id])
		# render :json => @users.count
		# return
	end

	def add_friend
		if params[:id]
			user = User.find(params[:id])
			if !user.nil? && session[:user_id]
				friend = Friend.where('(user_id = ? AND user_friend_id = ?) OR (user_id = ? AND user_friend_id = ?)', session[:user_id], user.id, user.id, session[:user_id]).first
				if friend.nil?
					friend = Friend.new(:user_id => session[:user_id], :user_friend_id => user.id, :is_accept => 0)
					if friend.save
						friend2 = Friend.where('user_id = ? AND user_friend_id = ?', friend.user_friend_id, friend.user_id).first
						if friend2.nil?
							friend2 = Friend.new(:user_id => friend.user_friend_id, :user_friend_id => friend.user_id, :is_accept => -1)
							if friend2.save
								render :json => {status: 1, message: "Add friend is successful."}
							else
								render :json => {status: 0, message: "Error."}
							end
						else
							if friend2.update_column(:is_accept, params[:status])
								render :json => {status: 1, message: "Add friend is successful."}
							else
								render :json => {status: 0, message: "Error."}
							end
						end
						# render :json => {status: 1, message: "Add friend is successful."}
					end
				else
					render :json => {status: 0, message: "This member added to your friend ."}
				end
			else
				render :json => {status: 0, message: "Not found this friend."}
			end
		else
			render :json => {status: 0, message: "Not found this friend."}
		end
		return
	end

	def update_status_friend
		if request.request_method() == 'POST'
			if params[:id]
				friend = Friend.where('user_id = ? AND user_friend_id = ?', params[:id], session[:user_id]).first
				if !friend.nil?
					if friend.is_accept != 2
						if friend.update_column(:is_accept, params[:status])
							friend2 = Friend.where('user_id = ? AND user_friend_id = ?', friend.user_friend_id, friend.user_id).first
							if friend2.nil?
								friend2 = Friend.new(:user_id => friend.user_friend_id, :user_friend_id => friend.user_id, :is_accept => params[:status])
								if friend2.save
									render :json => {status: 1, message: "Successful."}
								else
									render :json => {status: 0, message: "Error."}
								end
							else
								if friend2.update_column(:is_accept, params[:status])
									render :json => {status: 1, message: "Successful."}
								else
									render :json => {status: 0, message: "Error."}
								end
							end
						else
							render :json => {status: 0, message: "Don't Successful."}
						end
					end
				end
			end
		end
	end

	def add_friend_favorite
		if params[:id]
			user = User.find(params[:id])
			if !user.nil? && session[:user_id]
				friend = Friend.where('user_id = ? AND user_friend_id = ?', session[:user_id], user.id).first
				if !friend.nil?
					if friend.is_accept == 1
						if friend.update_column( :is_favorite, 1)
							me = User.find(session[:user_id])
							if !me.nil?
								me.points +=1
								me.save
							end
						end
						render :json => {status: 1, message: "Add to friend favorite is successful."}
					else
						render :json => {status: 0, message: "You don't add favorite for this friend."}
					end
				end
			else
				render :json => {status: 0, message: "Not found this friend."}
			end
		else
			render :json => {status: 0, message: "Not found this friend."}
		end
		return
	end

	def invite_friend
		render :json => params
		return
	end

	def profile
		if params[:id]
			@user = User.find(params[:id])
			if session[:user_id] != nil
				@friends = Friend.where('user_id = ? AND is_accept = ?',params[:id], 1)
				if session[:user_id].to_i == params[:id].to_i
					@friendsRequest = Friend.where('user_friend_id = ? AND is_accept = ?', session[:user_id], 0)
				end
				@favorites = Friend.where('user_id = ? AND is_favorite = ?', params[:id], 1)
			end
		else
			redirect_to root_path
		end
	end

	private
	  def user_params
	    params.require(:user).permit(:first_name, :last_name, :email, :password, :address, :phone)
	  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/list_friends.html.erb
<!--Projects Row -->
<div class="row">
  <div class="list-content" style="padding-top: 60px;">
    <div class="row" style="margin: 10px 0px;">
      <div class="col-sm-10">
          <form class="form-inline" id="frmSearch">
              <div class="form-group">
                  <label for="input-type">Search by: </label>
                  <select class="form-control" name="type" id="input-type">
                      <option value="name" <%= params[:type] == "name" ? 'selected="selected"' : '' %> >Name</option>
                      <option value="price" <%= params[:type] == "address" ? 'selected="selected"' : '' %> >Address</option>
                      <option value="phone" <%= params[:type] == "phone" ? 'selected="selected"' : '' %> >Phone</option>
                      <option value="email" <%= params[:type] == "email" ? 'selected="selected"' : '' %> >Email</option>
                  </select>
              </div>
              <div class="form-group">
                  <label for="input-keyword">Keyword</label>
                  <input type="text" name="keyword" class="form-control" id="input-keyword" placeholder="Tu khoa" value="<%= params[:keyword] %>">
              </div>
              <input type="hidden" name="sort" value="first_name">
              <input type="hidden" name="order" value="desc">
              <button type="submit" class="btn btn-default">Search</button>
          </form>
      </div>
      <div class="col-sm-2">
          <div class="dropdown">
              <button class="btn btn-default dropdown-toggle glyphicon glyphicon-sort" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Sap xep
              <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li><a href="#" class="sort-order" data-sort="name" data-order="desc">Name DESC</a></li>
                  <li><a href="#" class="sort-order" data-sort="name" data-order="asc">Name ASC</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#" class="sort-order" data-sort="created_at" data-order="desc">Created DESC</a></li>
                  <li><a href="#" class="sort-order" data-sort="created_at" data-order="asc">Created ASC</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#" class="sort-order" data-sort="friends" data-order="desc">Friends DESC</a></li>
                  <li><a href="#" class="sort-order" data-sort="friends" data-order="asc">Friends ASC</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#" class="sort-order" data-sort="favorites" data-order="desc">Favorites DESC</a></li>
                  <li><a href="#" class="sort-order" data-sort="favorites" data-order="asc">Favorites ASC</a></li>
              </ul>
          </div>
      </div>
  </div>
    <ul class="list-group">
      <li href="#" class="list-group-item title">
        Your friend zone
      </li>
        <% @users.each do |item| %>
          <% status = item.get_status_friend(session[:user_id]) %>
          <% favorite = item.get_favorite_friend(session[:user_id]) %>
          <% if status != 2 %>
          <li href="#" class="list-group-item text-left">
            <img class="img-thumbnail" src="http://bootdey.com/img/Content/User_for_snippets.png">
            <label class="name">
                <a href="<%= profile_path(item)%>"><%= item.fullname %></a> 
                <br>
                <%= item.email %><br>
                <%= item.get_friends_number %> friends <br>

            </label>
            <label class="pull-right">            
                <% if current_user %>
                  <% if status == nil %>
                    <a class="btn btn-success btn-xs glyphicon glyphicon-plus add-friend" data-remove-id="#remove-item-<%= item.id%>" data-url="<%= add_friend_path() %>" data-id="<%= item.id%>" href="#" title="Add friend"></a>
                    <a class="btn btn-danger btn-xs glyphicon glyphicon-remove update-status-friend hide" id="remove-item-<%= item.id%>" data-status="2" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Remove friend"></a>
                  <% elsif status == -1 %>
                    <a class="btn btn-danger btn-xs glyphicon glyphicon-remove update-status-friend" data-remove="true" data-status="2" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Remove friend"></a>
                  <% elsif status == 0 %>
                    <a class="btn btn-success btn-xs glyphicon glyphicon-saved update-status-friend" data-favorite-id="#favorite-item-<%= item.id%>" data-status="1" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Accept friend"></a>
                    <a class="btn btn-danger btn-xs glyphicon glyphicon-remove update-status-friend" data-remove="true" data-status="2" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Remove friend"></a>
                    <a class="btn btn-warning  btn-xs glyphicon glyphicon-heart add-favorite hide" data-remove-item="true" id="favorite-item-<%= item.id%>" data-url="<%= add_friend_favorite_path()%>" data-id="<%= item.id %>" href="#" title="Favorite"></a>
                  <% elsif status == 1 %>
                    <a class="btn btn-danger btn-xs glyphicon glyphicon-remove update-status-friend" data-remove="true" data-status="2" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Remove friend"></a>
                    <% if favorite == nil || favorite == 0 %>
                      <a class="btn btn-warning  btn-xs glyphicon glyphicon-heart add-favorite" data-remove-item="true" data-url="<%= add_friend_favorite_path()%>" data-id="<%= item.id %>" href="#" title="Favorite"></a>
                    <% end %>  
                  <% end %>
                <% else %>
                    <a class="btn btn-success btn-xs glyphicon glyphicon-plus add-friend-login" data-id="<%= item.id%>" href="<%= signin_path() %>" title="Add friend"></a>
                <% end %>
            </label>
            <div class="break"></div>
          </li>
          <% end %>
        <% end %>
          <!-- Pagination -->      
        <li href="#" class="list-group-item text-center">
          <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
        </li>
      
      <!-- <li href="#" class="list-group-item text-left">
        <a class="btn btn-block btn-primary">
            <i class="glyphicon glyphicon-refresh"></i>
            Load more...
        </a>
      </li> -->
    </ul>
  </div>
</div>
<!-- /.row -->
<hr>
<!-- /.row

app/views/users/profile.html.erb
<div class="col-lg-12 col-sm-12">
  <div class="card hovercard">
    <div class="card-background">
      <img class="card-bkimg" alt="" src="/avatar.jpeg">
      <!-- http://lorempixel.com/850/280/people/9/ -->
    </div>
    <div class="useravatar">
      <img alt="" src="/avatar.jpeg">
    </div>
    <div class="card-info"> <span class="card-title"><%= @user.fullname %></span>
  </div>
</div>
<div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">
  <div class="btn-group" role="group">
    <button type="button" id="stars" class="btn btn-primary" href="#tab1" data-toggle="tab"><span class="glyphicon glyphicon-star" aria-hidden="true"></span>
    <div class="hidden-xs">Profile</div>
    </button>
  </div>
  <% if session[:user_id] != nil %>
  <div class="btn-group" role="group">
    <button type="button" id="stars" class="btn btn-default" href="#tab2" data-toggle="tab"><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
    <div class="hidden-xs">Friends</div>
    </button>
  </div>
  <% if session[:user_id].to_i == params[:id].to_i %>
  <div class="btn-group" role="group">
    <button type="button" id="stars" class="btn btn-default" href="#tab3" data-toggle="tab"><span class="glyphicon glyphicon-circle-arrow-down" aria-hidden="true"></span>
    <div class="hidden-xs">Friends request</div>
    </button>
  </div>
  <% end %>
  <div class="btn-group" role="group">
    <button type="button" id="favorites" class="btn btn-default" href="#tab4" data-toggle="tab"><span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
    <div class="hidden-xs">Favorites</div>
    </button>
  </div>
  <% end %>
</div>
<div class="well">
  <div class="tab-content">
    <div class="tab-pane fade in active" id="tab1">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 toppad" >
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @user.fullname %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"> <img alt="User Pic" src="http://babyinfoforyou.com/wp-content/uploads/2014/10/avatar-300x300.png" class="img-circle img-responsive"> </div>
                <div class=" col-md-9 col-lg-9 ">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>First name:</td>
                        <td><%= @user.first_name %></td>
                      </tr>
                      <tr>
                        <td>Last name:</td>
                        <td><%= @user.last_name %></td>
                      </tr>
                      <tr>
                        <td>Address: </td>
                        <td><%= @user.address %></td>
                      </tr>
                      <tr>
                        <td>Phone</td>
                        <td><%= @user.phone %></td>
                      </tr>
                      <tr>
                        <td>Email</td>
                        <td><a href="mailto:<%= @user.email %>"><%= @user.email %></a></td>
                      </tr>
                      <tr>
                        <td>Points: </td>
                        <td><%= @user.points %></td>
                      </tr>
                    </tbody>
                  </table>
                  
                  <!-- <a href="#" class="btn btn-primary">My Sales Performance</a>
                  <a href="#" class="btn btn-primary">Team Sales Performance</a> -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% if session[:user_id] != nil %>
    <div class="tab-pane fade in" id="tab2">
      <div class="jumbotron list-content">
        <ul class="list-group">
          <% if @friends.count > 0 %>
            <% @friends.each do |object| %>
              <% item = object.user_friend%>
              <% status = item.get_status_friend(session[:user_id]) %>
              <% favorite = item.get_favorite_friend(session[:user_id]) %>
            <li href="#" class="list-group-item text-left">
              <img class="img-thumbnail" src="http://bootdey.com/img/Content/User_for_snippets.png">
              <label class="name">
                  <a href="<%= profile_path(item)%>"><%= item.fullname %></a> 
                  <br>
                  <%= item.email %><br>
                  <%= item.get_friends_number %> friends <br>
              </label>
              <label class="pull-right">            
                  <% if current_user %>
                    <a class="btn btn-danger btn-xs glyphicon glyphicon-remove update-status-friend" data-remove="true" data-status="2" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Remove friend"></a>
                      <% if favorite == nil || favorite == 0 %>
                        <a class="btn btn-warning  btn-xs glyphicon glyphicon-heart add-favorite" data-remove-item="true" data-url="<%= add_friend_favorite_path()%>" data-id="<%= item.id %>" href="#" title="Favorite"></a>
                      <% end %> 
                  <% else %>
                    <a class="btn btn-success btn-xs glyphicon glyphicon-plus add-friend-login" data-id="<%= item.id%>" href="<%= signin_path() %>" title="Add friend"></a>
                  <% end %>
              </label>
              <div class="break"></div>
            </li>
            <% end %>
          <% else %>
            <li href="#" class="list-group-item text-center">
              Not found
            </li>
          <% end %>
            <!-- Pagination -->      
          <li href="#" class="list-group-item text-center">
            
          </li>
          <!-- <li href="#" class="list-group-item text-left">
            <a class="btn btn-block btn-primary">
                <i class="glyphicon glyphicon-refresh"></i>
                Load more...
            </a>
          </li> -->
        </ul>
      </div>
    </div>
    <% if session[:user_id].to_i == params[:id].to_i %>
    <div class="tab-pane fade in" id="tab3">
      <div class="jumbotron list-content">
        <ul class="list-group">
          <%  if @friendsRequest.count > 0 %>
            <% @friendsRequest.each do |object| %>
              <% item = object.user%>
              <% status = item.get_status_friend(session[:user_id]) %>
              <% favorite = item.get_favorite_friend(session[:user_id]) %>
              <li href="#" class="list-group-item text-left">
                <img class="img-thumbnail" src="http://bootdey.com/img/Content/User_for_snippets.png">
                <label class="name">
                    <a href="<%= profile_path(item)%>"><%= item.fullname %></a> 
                    <br>
                    <%= item.email %><br>
                    <%= item.get_friends_number %> friends <br>
                </label>
                <label class="pull-right">            
                    <% if current_user %>
                      <a class="btn btn-success btn-xs glyphicon glyphicon-saved update-status-friend" data-favorite-id="#favorite-item-<%= item.id%>" data-status="1" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Accept friend"></a>
                      <a class="btn btn-danger btn-xs glyphicon glyphicon-remove update-status-friend" data-remove="true" data-status="2" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Remove friend"></a>
                      <a class="btn btn-warning  btn-xs glyphicon glyphicon-heart add-favorite hide" data-remove-item="true" id="favorite-item-<%= item.id%>" data-url="<%= add_friend_favorite_path()%>" data-id="<%= item.id %>" href="#" title="Favorite"></a>
                    <% else %>
                      <a class="btn btn-success btn-xs glyphicon glyphicon-plus add-friend-login" data-id="<%= item.id%>" href="<%= signin_path() %>" title="Add friend"></a>
                    <% end %>
                </label>
                <div class="break"></div>
              </li>
            <% end %>
          <% else %>
            <li href="#" class="list-group-item text-center">
              Not found
            </li>
          <% end %>
            <!-- Pagination -->      
          <li href="#" class="list-group-item text-center">
            
          </li>
          <!-- <li href="#" class="list-group-item text-left">
            <a class="btn btn-block btn-primary">
                <i class="glyphicon glyphicon-refresh"></i>
                Load more...
            </a>
          </li> -->
        </ul>
      </div>
    </div>
    <% end %>
    <div class="tab-pane fade in" id="tab4">
      <div class="jumbotron list-content">
        <ul class="list-group">
          <% if @favorites.count > 0 %>
            <% @favorites.each do |object| %>
              <% item = object.user_friend%>
              <% status = item.get_status_friend(session[:user_id]) %>
              <% favorite = item.get_favorite_friend(session[:user_id]) %>
              <li href="#" class="list-group-item text-left">
                <img class="img-thumbnail" src="http://bootdey.com/img/Content/User_for_snippets.png">
                <label class="name">
                    <a href="<%= profile_path(item)%>"><%= item.fullname %></a> <br>
                    <%= item.email %><br>
                    <%= item.get_friends_number %> friends <br>
                </label>
                <label class="pull-right">            
                    <% if current_user %>
                        <a class="btn btn-danger btn-xs glyphicon glyphicon-remove update-status-friend" data-remove="true" data-status="2" data-url="<%= update_status_friend_path(item) %>" data-id="<%= item.id%>" href="#" title="Remove friend"></a>
                    <% else %>
                      <a class="btn btn-success btn-xs glyphicon glyphicon-plus add-friend-login" data-id="<%= item.id%>" href="<%= signin_path() %>" title="Add friend"></a>
                    <% end %>
                </label>
                <div class="break"></div>
              </li>
            <% end %>
          <% else %>
            <li href="#" class="list-group-item text-center">
              Not found
            </li>
          <% end %>
            <!-- Pagination -->      
          <li href="#" class="list-group-item text-center">
            
          </li>
          <!-- <li href="#" class="list-group-item text-left">
            <a class="btn btn-block btn-primary">
                <i class="glyphicon glyphicon-refresh"></i>
                Load more...
            </a>
          </li> -->
        </ul>
      </div>
    </div>

    <% end %>
  </div>
</div>

</div>