config/routes.rb
Rails.application.routes.draw do

  root to: 'users#list_friends'
  match '/register', to: 'users#signup', via: [:get, :post], as: :signup
  match '/signin', to: 'users#signin', via: [:get, :post], as: :signin
  get '/logout', to: 'users#logout', as: :logout
  get '/find-friends', to: 'users#find_friend', as: :find_friend
  get '/friends', to: 'users#list_friends', as: :friends
  post '/add-friend', to: 'users#add_friend', as: :add_friend
  post '/update-status-friend/:id', to: 'users#update_status_friend', as: :update_status_friend
  post '/add-friend-favorite', to: 'users#add_friend_favorite', as: :add_friend_favorite
  post '/invite-friend', to: 'users#invite_friend', as: :invite_friend

  get '/profile/:id', to: 'users#profile', as: :profile
end

app/views/layouts/application-.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SocialNetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Social network</title>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->


    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag    'css/bootstrap.min.css', media: 'all', 'data-turbolinks-track' => true %>
    <!-- Custom CSS -->
    <%= stylesheet_link_tag    'css/shop-homepage.css', media: 'all', 'data-turbolinks-track' => true %>

    <%= stylesheet_link_tag    'signup.css', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'client.css', media: 'all', 'data-turbolinks-track' => true %>

    <!-- jQuery -->
    <%= javascript_include_tag 'js/jquery.js', 'data-turbolinks-track' => true %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag 'js/bootstrap.min.js', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap/js/bootstrap.autocomplete.min.js', 'data-turbolinks-track' => true %>
    
    <!-- Notification -->
    <%= javascript_include_tag 'bootstrap-notify-3.1.3/dist/bootstrap-notify.min.js', 'data-turbolinks-track' => true %>
    <!-- Bootbox  -->
    <%= javascript_include_tag 'bootbox/bootbox.min.js', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'js/custom.js', 'data-turbolinks-track' => true %>
    

	<%= csrf_meta_tags %>
	<meta id="authenticity_token" value="<%= form_authenticity_token %>">
</head>

<body>
    <div id="form-login" class="hide">
        <%= form_for(:session, url: signin_path, :html => {class: "form-signin"}) do |item| %>
            <div class="panel panel-danger hide" id="message-notification-dialog">
              <div class="panel-body">
              </div>
            </div>
            <%= item.label :email, class: "sr-only", for: "input-email" %>
            <%= item.email_field :email, class: "form-control", id: "input-email", placeholder: "Email address", required: true, autofocus: true %>
            <%= item.label :password, class: "sr-only", for: "input-password" %>
            <%= item.password_field :password, class: "form-control", id: "input-password", placeholder: "Password", required: true %>
            <%= item.hidden_field :id, id: "id-item-friend" %>
            <div class="checkbox">
                <a href='<%= signup_path() %>' class="btn btn-block btn-social btn-facebook">
                    <span class="fa fa-facebook"></span> Sign up a account
                </a>
            </div>
        <% end %>
    </div>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path() %>">Social network</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<%= friends_path() %>">Find friends</a>
                    </li>
                    <% if current_user %>
                        <li>
                            <a href="<%= profile_path(current_user.id) %>"><%= current_user.email %></a>
                        </li>
                        <li>
                            <a href="<%= logout_path() %>">Logout</a>
                        </li>
                    <% else %>
                    <li>
                        <a href="<%= signup_path() %>">Register</a>
                    </li>
                    <li>
                        <a href="<%= signin_path() %>">Login</a>
                    </li>
                    <% end %>
                </ul>
                <form class="navbar-form navbar-right">
                    <input class="form-control typeahead" placeholder="Search..." type="text" data-provide="typeahead" autocomplete="off">
                  </form>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <%= yield %>

    </div>
    <!-- /.container -->

    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Social network 2016</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

</body>

</html>